/**
 * Mock recipe data for demo mode.
 * These get loaded into the local store so you can see and interact with
 * recipes without needing a real Supabase backend.
 */

import type { Recipe } from '@/types/database';

const DEMO_USER_ID = 'demo-user-001';

function makeId(index: number) {
  return `seed-recipe-${String(index).padStart(3, '0')}`;
}

function ts(daysAgo: number) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export const seedRecipes: Recipe[] = [
  // 1 — Japanese
  {
    id: makeId(1),
    user_id: DEMO_USER_ID,
    title: 'Chicken Katsu Curry',
    description: 'Crispy panko-coated chicken cutlet served over rice with a rich Japanese curry sauce.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 20,
    cook_time_minutes: 35,
    calories_per_serving: 620,
    protein_per_serving: 35,
    carbs_per_serving: 72,
    fat_per_serving: 20,
    tags: ['japanese', 'curry', 'chicken'],
    ingredients: [
      { name: 'chicken breast', quantity: 4, unit: 'pieces', category: 'protein' },
      { name: 'panko breadcrumbs', quantity: 1, unit: 'cup', category: 'pantry' },
      { name: 'egg', quantity: 2, unit: 'pieces', category: 'dairy' },
      { name: 'flour', quantity: 0.5, unit: 'cup', category: 'pantry' },
      { name: 'Japanese curry roux', quantity: 1, unit: 'box', category: 'pantry' },
      { name: 'potato', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'carrot', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'steamed rice', quantity: 4, unit: 'cups', category: 'grains' },
    ],
    instructions: [
      'Slice chicken breasts in half horizontally to make thin cutlets.',
      'Set up a breading station: flour, beaten eggs, and panko in separate bowls.',
      'Coat each cutlet in flour, dip in egg, then press into panko.',
      'Fry cutlets in oil over medium heat for 4-5 minutes per side until golden.',
      'In a pot, sauté diced onion, carrot, and potato until softened.',
      'Add water and bring to a boil, then simmer until vegetables are tender.',
      'Break curry roux into the pot and stir until thickened.',
      'Slice the chicken katsu and serve over rice with curry sauce.',
    ],
    created_at: ts(1),
    updated_at: ts(1),
  },

  // 2 — Italian
  {
    id: makeId(2),
    user_id: DEMO_USER_ID,
    title: 'Spaghetti Carbonara',
    description: 'Classic Roman pasta with eggs, Pecorino Romano, guanciale, and black pepper.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    calories_per_serving: 550,
    protein_per_serving: 25,
    carbs_per_serving: 60,
    fat_per_serving: 22,
    tags: ['italian', 'pasta', 'quick'],
    ingredients: [
      { name: 'spaghetti', quantity: 400, unit: 'g', category: 'grains' },
      { name: 'guanciale or pancetta', quantity: 200, unit: 'g', category: 'protein' },
      { name: 'egg yolks', quantity: 4, unit: 'pieces', category: 'dairy' },
      { name: 'whole egg', quantity: 1, unit: 'piece', category: 'dairy' },
      { name: 'Pecorino Romano', quantity: 100, unit: 'g', category: 'dairy' },
      { name: 'black pepper', quantity: 2, unit: 'tsp', category: 'spices' },
    ],
    instructions: [
      'Boil a large pot of salted water and cook spaghetti until al dente.',
      'While pasta cooks, cut guanciale into small strips and cook in a dry pan until crispy.',
      'Whisk together egg yolks, whole egg, grated Pecorino, and black pepper.',
      'Drain pasta, reserving 1 cup of pasta water.',
      'Add hot pasta to the guanciale pan (heat OFF) and toss quickly.',
      'Pour the egg mixture over the pasta and toss vigorously, adding pasta water as needed to create a creamy sauce.',
      'Serve immediately with extra Pecorino and pepper on top.',
    ],
    created_at: ts(2),
    updated_at: ts(2),
  },

  // 3 — Mexican
  {
    id: makeId(3),
    user_id: DEMO_USER_ID,
    title: 'Chicken Tacos al Pastor',
    description: 'Smoky, sweet marinated chicken tacos inspired by the famous al pastor preparation.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 30,
    cook_time_minutes: 15,
    calories_per_serving: 420,
    protein_per_serving: 32,
    carbs_per_serving: 40,
    fat_per_serving: 14,
    tags: ['mexican', 'tacos', 'chicken'],
    ingredients: [
      { name: 'chicken thighs', quantity: 600, unit: 'g', category: 'protein' },
      { name: 'pineapple', quantity: 1, unit: 'cup', category: 'produce' },
      { name: 'corn tortillas', quantity: 12, unit: 'pieces', category: 'grains' },
      { name: 'achiote paste', quantity: 2, unit: 'tbsp', category: 'spices' },
      { name: 'lime', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'white onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'cilantro', quantity: 0.5, unit: 'cup', category: 'produce' },
      { name: 'chipotle in adobo', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Blend achiote paste, chipotle, juice of 1 lime, and a splash of pineapple juice to make the marinade.',
      'Coat chicken thighs in the marinade and refrigerate for at least 20 minutes.',
      'Grill or pan-sear chicken until charred and cooked through, about 6 minutes per side.',
      'Grill pineapple slices until caramelized.',
      'Chop chicken and pineapple into small pieces.',
      'Warm tortillas on a dry skillet.',
      'Assemble tacos with chicken, pineapple, diced onion, cilantro, and a squeeze of lime.',
    ],
    created_at: ts(3),
    updated_at: ts(3),
  },

  // 4 — Thai
  {
    id: makeId(4),
    user_id: DEMO_USER_ID,
    title: 'Pad Thai',
    description: 'Stir-fried rice noodles with shrimp, tamarind sauce, peanuts, and lime.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 2,
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    calories_per_serving: 490,
    protein_per_serving: 28,
    carbs_per_serving: 58,
    fat_per_serving: 16,
    tags: ['thai', 'noodles', 'shrimp'],
    ingredients: [
      { name: 'rice noodles', quantity: 200, unit: 'g', category: 'grains' },
      { name: 'shrimp', quantity: 200, unit: 'g', category: 'protein' },
      { name: 'tamarind paste', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'fish sauce', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'sugar', quantity: 1, unit: 'tbsp', category: 'pantry' },
      { name: 'egg', quantity: 2, unit: 'pieces', category: 'dairy' },
      { name: 'bean sprouts', quantity: 1, unit: 'cup', category: 'produce' },
      { name: 'roasted peanuts', quantity: 0.25, unit: 'cup', category: 'pantry' },
      { name: 'lime', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'green onion', quantity: 2, unit: 'stalks', category: 'produce' },
    ],
    instructions: [
      'Soak rice noodles in warm water for 15 minutes, then drain.',
      'Mix tamarind paste, fish sauce, and sugar to make the pad thai sauce.',
      'Heat oil in a wok over high heat. Cook shrimp until pink, then set aside.',
      'Crack eggs into the wok and scramble lightly.',
      'Add drained noodles and the sauce. Toss until noodles absorb the sauce.',
      'Return shrimp, add bean sprouts and green onion. Toss briefly.',
      'Serve with crushed peanuts and a lime wedge.',
    ],
    created_at: ts(4),
    updated_at: ts(4),
  },

  // 5 — Indian
  {
    id: makeId(5),
    user_id: DEMO_USER_ID,
    title: 'Butter Chicken (Murgh Makhani)',
    description: 'Tender chicken in a creamy, mildly spiced tomato-butter sauce — an Indian classic.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 20,
    cook_time_minutes: 30,
    calories_per_serving: 480,
    protein_per_serving: 34,
    carbs_per_serving: 18,
    fat_per_serving: 30,
    tags: ['indian', 'curry', 'chicken'],
    ingredients: [
      { name: 'chicken thighs', quantity: 800, unit: 'g', category: 'protein' },
      { name: 'plain yogurt', quantity: 0.5, unit: 'cup', category: 'dairy' },
      { name: 'garam masala', quantity: 2, unit: 'tsp', category: 'spices' },
      { name: 'turmeric', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'crushed tomatoes', quantity: 400, unit: 'g', category: 'pantry' },
      { name: 'butter', quantity: 4, unit: 'tbsp', category: 'dairy' },
      { name: 'heavy cream', quantity: 0.5, unit: 'cup', category: 'dairy' },
      { name: 'garlic', quantity: 4, unit: 'cloves', category: 'produce' },
      { name: 'ginger', quantity: 1, unit: 'tbsp', category: 'produce' },
      { name: 'kashmiri chili powder', quantity: 1, unit: 'tsp', category: 'spices' },
    ],
    instructions: [
      'Marinate chicken in yogurt, garam masala, turmeric, and chili powder for 15 minutes.',
      'Sear marinated chicken in a hot pan until browned on both sides. Set aside.',
      'In the same pan, melt butter and sauté minced garlic and ginger until fragrant.',
      'Add crushed tomatoes and simmer for 15 minutes until thickened.',
      'Blend the sauce until smooth (or use an immersion blender).',
      'Return sauce to pan, add chicken, and simmer for 10 minutes.',
      'Stir in heavy cream, season with salt, and serve with naan or rice.',
    ],
    created_at: ts(5),
    updated_at: ts(5),
  },

  // 6 — Korean
  {
    id: makeId(6),
    user_id: DEMO_USER_ID,
    title: 'Bibimbap',
    description: 'Korean mixed rice bowl with seasoned vegetables, beef, a fried egg, and gochujang sauce.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 2,
    prep_time_minutes: 25,
    cook_time_minutes: 15,
    calories_per_serving: 560,
    protein_per_serving: 30,
    carbs_per_serving: 65,
    fat_per_serving: 18,
    tags: ['korean', 'rice bowl', 'beef'],
    ingredients: [
      { name: 'steamed rice', quantity: 2, unit: 'cups', category: 'grains' },
      { name: 'ground beef', quantity: 200, unit: 'g', category: 'protein' },
      { name: 'spinach', quantity: 1, unit: 'cup', category: 'produce' },
      { name: 'carrot', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'zucchini', quantity: 0.5, unit: 'piece', category: 'produce' },
      { name: 'bean sprouts', quantity: 1, unit: 'cup', category: 'produce' },
      { name: 'egg', quantity: 2, unit: 'pieces', category: 'dairy' },
      { name: 'gochujang', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp', category: 'pantry' },
      { name: 'sesame oil', quantity: 1, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Season ground beef with soy sauce and sesame oil, then cook in a pan until browned.',
      'Blanch spinach and bean sprouts separately, then season each with a pinch of salt and sesame oil.',
      'Julienne carrot and zucchini, then sauté each briefly.',
      'Fry eggs sunny-side up.',
      'Place steamed rice in bowls. Arrange beef and vegetables on top in sections.',
      'Top with a fried egg and a generous dollop of gochujang.',
      'Mix everything together before eating.',
    ],
    created_at: ts(6),
    updated_at: ts(6),
  },

  // 7 — Chinese
  {
    id: makeId(7),
    user_id: DEMO_USER_ID,
    title: 'Mapo Tofu',
    description: 'Sichuan-style silken tofu in a fiery, numbing sauce with ground pork.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 3,
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    calories_per_serving: 350,
    protein_per_serving: 22,
    carbs_per_serving: 15,
    fat_per_serving: 24,
    tags: ['chinese', 'sichuan', 'tofu', 'spicy'],
    ingredients: [
      { name: 'silken tofu', quantity: 400, unit: 'g', category: 'protein' },
      { name: 'ground pork', quantity: 150, unit: 'g', category: 'protein' },
      { name: 'doubanjiang (fermented bean paste)', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'Sichuan peppercorns', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'produce' },
      { name: 'ginger', quantity: 1, unit: 'tsp', category: 'produce' },
      { name: 'green onion', quantity: 2, unit: 'stalks', category: 'produce' },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp', category: 'pantry' },
      { name: 'cornstarch', quantity: 1, unit: 'tsp', category: 'pantry' },
    ],
    instructions: [
      'Cut tofu into 1-inch cubes and gently blanch in salted water for 2 minutes. Drain.',
      'Toast Sichuan peppercorns in a dry wok, then grind to a powder.',
      'Cook ground pork in the wok until browned and crumbly.',
      'Add doubanjiang, minced garlic, and ginger. Stir-fry until fragrant and oil turns red.',
      'Pour in a small amount of water or stock, add soy sauce, and bring to a simmer.',
      'Gently add tofu cubes and simmer for 5 minutes.',
      'Thicken with a cornstarch slurry, sprinkle with Sichuan pepper and green onion. Serve over rice.',
    ],
    created_at: ts(7),
    updated_at: ts(7),
  },

  // 8 — Mediterranean / Greek
  {
    id: makeId(8),
    user_id: DEMO_USER_ID,
    title: 'Greek Chicken Souvlaki',
    description: 'Lemon-herb marinated chicken skewers served with tzatziki, pita, and fresh salad.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 25,
    cook_time_minutes: 12,
    calories_per_serving: 380,
    protein_per_serving: 36,
    carbs_per_serving: 28,
    fat_per_serving: 14,
    tags: ['greek', 'grilled', 'chicken', 'healthy'],
    ingredients: [
      { name: 'chicken breast', quantity: 600, unit: 'g', category: 'protein' },
      { name: 'lemon', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'dried oregano', quantity: 1, unit: 'tbsp', category: 'spices' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'produce' },
      { name: 'Greek yogurt', quantity: 1, unit: 'cup', category: 'dairy' },
      { name: 'cucumber', quantity: 0.5, unit: 'piece', category: 'produce' },
      { name: 'pita bread', quantity: 4, unit: 'pieces', category: 'grains' },
      { name: 'tomato', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'red onion', quantity: 0.5, unit: 'piece', category: 'produce' },
    ],
    instructions: [
      'Cut chicken into cubes. Marinate in olive oil, lemon juice, oregano, and minced garlic for 20 minutes.',
      'Thread chicken onto skewers.',
      'Make tzatziki: grate cucumber, squeeze out water, mix with yogurt, a drizzle of olive oil, and a pinch of salt.',
      'Grill skewers on high heat for 5-6 minutes per side until charred.',
      'Warm pita bread on the grill.',
      'Serve skewers on pita with tzatziki, sliced tomato, and red onion.',
    ],
    created_at: ts(8),
    updated_at: ts(8),
  },

  // 9 — Vietnamese
  {
    id: makeId(9),
    user_id: DEMO_USER_ID,
    title: 'Pho Bo (Beef Pho)',
    description: 'Vietnamese beef noodle soup with aromatic star anise and cinnamon broth.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 15,
    cook_time_minutes: 60,
    calories_per_serving: 420,
    protein_per_serving: 30,
    carbs_per_serving: 50,
    fat_per_serving: 10,
    tags: ['vietnamese', 'soup', 'beef', 'noodles'],
    ingredients: [
      { name: 'beef bones', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'beef sirloin (thinly sliced)', quantity: 300, unit: 'g', category: 'protein' },
      { name: 'rice noodles (banh pho)', quantity: 400, unit: 'g', category: 'grains' },
      { name: 'star anise', quantity: 3, unit: 'pieces', category: 'spices' },
      { name: 'cinnamon stick', quantity: 1, unit: 'piece', category: 'spices' },
      { name: 'ginger', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'fish sauce', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'bean sprouts', quantity: 1, unit: 'cup', category: 'produce' },
      { name: 'Thai basil', quantity: 0.5, unit: 'cup', category: 'produce' },
      { name: 'lime', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'hoisin sauce', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Char ginger and onion under the broiler or over an open flame until blackened.',
      'Boil beef bones in water, then drain and rinse to remove impurities.',
      'In a large pot, cover bones with fresh water. Add charred ginger, onion, star anise, and cinnamon.',
      'Simmer broth on low for at least 45 minutes. Skim any foam.',
      'Season broth with fish sauce and a pinch of sugar.',
      'Cook rice noodles according to package directions.',
      'Place noodles in bowls, top with raw sliced beef.',
      'Ladle boiling broth over the beef (it cooks instantly). Serve with bean sprouts, basil, lime, and hoisin.',
    ],
    created_at: ts(9),
    updated_at: ts(9),
  },

  // 10 — Middle Eastern
  {
    id: makeId(10),
    user_id: DEMO_USER_ID,
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce — a popular North African and Middle Eastern dish.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 3,
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    calories_per_serving: 280,
    protein_per_serving: 16,
    carbs_per_serving: 18,
    fat_per_serving: 16,
    tags: ['middle eastern', 'eggs', 'vegetarian', 'breakfast'],
    ingredients: [
      { name: 'eggs', quantity: 6, unit: 'pieces', category: 'dairy' },
      { name: 'canned tomatoes', quantity: 400, unit: 'g', category: 'pantry' },
      { name: 'red bell pepper', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'produce' },
      { name: 'cumin', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'paprika', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'feta cheese', quantity: 50, unit: 'g', category: 'dairy' },
      { name: 'crusty bread', quantity: 1, unit: 'loaf', category: 'grains' },
    ],
    instructions: [
      'Heat olive oil in a deep skillet. Sauté diced onion and bell pepper until softened.',
      'Add minced garlic, cumin, and paprika. Cook for 1 minute.',
      'Pour in canned tomatoes, break them up, and simmer for 15 minutes until thickened.',
      'Make 6 small wells in the sauce and crack an egg into each.',
      'Cover and cook on low heat for 6-8 minutes until egg whites are set but yolks are still runny.',
      'Crumble feta over the top and serve straight from the skillet with bread.',
    ],
    created_at: ts(10),
    updated_at: ts(10),
  },

  // 11 — Ethiopian
  {
    id: makeId(11),
    user_id: DEMO_USER_ID,
    title: 'Doro Wat (Ethiopian Chicken Stew)',
    description: 'Rich, slow-cooked Ethiopian chicken stew with berbere spice and hard-boiled eggs.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 15,
    cook_time_minutes: 50,
    calories_per_serving: 440,
    protein_per_serving: 38,
    carbs_per_serving: 22,
    fat_per_serving: 22,
    tags: ['ethiopian', 'stew', 'chicken', 'spicy'],
    ingredients: [
      { name: 'chicken drumsticks', quantity: 8, unit: 'pieces', category: 'protein' },
      { name: 'onion', quantity: 3, unit: 'pieces', category: 'produce' },
      { name: 'berbere spice mix', quantity: 3, unit: 'tbsp', category: 'spices' },
      { name: 'butter (niter kibbeh or regular)', quantity: 3, unit: 'tbsp', category: 'dairy' },
      { name: 'tomato paste', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'garlic', quantity: 4, unit: 'cloves', category: 'produce' },
      { name: 'ginger', quantity: 1, unit: 'tbsp', category: 'produce' },
      { name: 'hard-boiled eggs', quantity: 4, unit: 'pieces', category: 'dairy' },
      { name: 'lemon juice', quantity: 2, unit: 'tbsp', category: 'produce' },
    ],
    instructions: [
      'Finely dice onions — this is key. Cook them in a dry pot on medium heat, stirring often, until deeply caramelized (about 15 minutes).',
      'Add butter, garlic, and ginger. Cook for 2 minutes.',
      'Stir in berbere spice and tomato paste. Cook for another 3 minutes.',
      'Score the chicken with a knife and rub with lemon juice.',
      'Add chicken to the pot with a cup of water. Cover and simmer for 30-40 minutes.',
      'Add peeled hard-boiled eggs in the last 10 minutes to soak up the sauce.',
      'Serve with injera (spongy flatbread) or steamed rice.',
    ],
    created_at: ts(11),
    updated_at: ts(11),
  },

  // 12 — French
  {
    id: makeId(12),
    user_id: DEMO_USER_ID,
    title: 'Ratatouille',
    description: 'Provençal vegetable stew with layers of eggplant, zucchini, tomato, and bell pepper.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 20,
    cook_time_minutes: 45,
    calories_per_serving: 180,
    protein_per_serving: 4,
    carbs_per_serving: 22,
    fat_per_serving: 9,
    tags: ['french', 'vegetarian', 'healthy', 'vegan'],
    ingredients: [
      { name: 'eggplant', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'zucchini', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'red bell pepper', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'yellow bell pepper', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'tomatoes', quantity: 4, unit: 'pieces', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'garlic', quantity: 4, unit: 'cloves', category: 'produce' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'herbes de Provence', quantity: 1, unit: 'tbsp', category: 'spices' },
    ],
    instructions: [
      'Dice all vegetables into similar-sized pieces.',
      'Sauté onion and garlic in olive oil until fragrant.',
      'Add bell peppers and cook for 5 minutes.',
      'Add eggplant and zucchini, cook for another 5 minutes.',
      'Add diced tomatoes and herbes de Provence. Season with salt and pepper.',
      'Cover and simmer on low heat for 30-35 minutes, stirring occasionally.',
      'Serve warm as a main dish or as a side. Great with crusty bread.',
    ],
    created_at: ts(12),
    updated_at: ts(12),
  },

  // 13 — Brazilian
  {
    id: makeId(13),
    user_id: DEMO_USER_ID,
    title: 'Feijoada (Brazilian Black Bean Stew)',
    description: 'Brazil\'s national dish — a hearty black bean stew with pork and sausage, served with rice and orange slices.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 6,
    prep_time_minutes: 20,
    cook_time_minutes: 90,
    calories_per_serving: 580,
    protein_per_serving: 38,
    carbs_per_serving: 48,
    fat_per_serving: 24,
    tags: ['brazilian', 'stew', 'beans', 'pork'],
    ingredients: [
      { name: 'dried black beans', quantity: 500, unit: 'g', category: 'pantry' },
      { name: 'pork shoulder', quantity: 300, unit: 'g', category: 'protein' },
      { name: 'smoked sausage (linguiça)', quantity: 200, unit: 'g', category: 'protein' },
      { name: 'bacon', quantity: 100, unit: 'g', category: 'protein' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'garlic', quantity: 5, unit: 'cloves', category: 'produce' },
      { name: 'bay leaves', quantity: 3, unit: 'pieces', category: 'spices' },
      { name: 'orange', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'steamed rice', quantity: 3, unit: 'cups', category: 'grains' },
    ],
    instructions: [
      'Soak black beans overnight in plenty of water, then drain.',
      'Cut pork shoulder into chunks and slice sausage into rounds.',
      'In a large pot, cook bacon until the fat renders. Add onion and garlic.',
      'Add pork, sausage, drained beans, bay leaves, and enough water to cover.',
      'Bring to a boil, then reduce heat and simmer for about 1.5 hours until beans are tender.',
      'Remove a cup of beans, mash them, and stir back in to thicken the stew.',
      'Serve over rice with orange slices on the side — the citrus cuts through the richness.',
    ],
    created_at: ts(13),
    updated_at: ts(13),
  },

  // 14 — Moroccan
  {
    id: makeId(14),
    user_id: DEMO_USER_ID,
    title: 'Chicken Tagine with Preserved Lemons',
    description: 'Aromatic Moroccan slow-cooked chicken with olives, preserved lemons, and warm spices.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 15,
    cook_time_minutes: 50,
    calories_per_serving: 400,
    protein_per_serving: 34,
    carbs_per_serving: 14,
    fat_per_serving: 24,
    tags: ['moroccan', 'chicken', 'tagine', 'slow-cooked'],
    ingredients: [
      { name: 'chicken thighs (bone-in)', quantity: 8, unit: 'pieces', category: 'protein' },
      { name: 'preserved lemons', quantity: 2, unit: 'pieces', category: 'pantry' },
      { name: 'green olives', quantity: 0.5, unit: 'cup', category: 'pantry' },
      { name: 'onion', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'garlic', quantity: 4, unit: 'cloves', category: 'produce' },
      { name: 'ground ginger', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'turmeric', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'saffron threads', quantity: 1, unit: 'pinch', category: 'spices' },
      { name: 'cilantro', quantity: 0.5, unit: 'cup', category: 'produce' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Season chicken with salt, ginger, turmeric, and saffron.',
      'In a tagine or heavy pot, heat olive oil and brown chicken on all sides.',
      'Remove chicken. Sauté sliced onions and garlic until softened.',
      'Return chicken, add a splash of water, cover, and cook on low for 35 minutes.',
      'Rinse preserved lemons, discard the pulp, and cut the rind into strips.',
      'Add preserved lemon rind and olives in the last 10 minutes of cooking.',
      'Garnish with fresh cilantro and serve with couscous or bread.',
    ],
    created_at: ts(14),
    updated_at: ts(14),
  },

  // 15 — Filipino
  {
    id: makeId(15),
    user_id: DEMO_USER_ID,
    title: 'Chicken Adobo',
    description: 'Filipino braised chicken in soy sauce and vinegar — savory, tangy, and incredibly easy.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 10,
    cook_time_minutes: 35,
    calories_per_serving: 380,
    protein_per_serving: 32,
    carbs_per_serving: 8,
    fat_per_serving: 24,
    tags: ['filipino', 'chicken', 'braised', 'easy'],
    ingredients: [
      { name: 'chicken thighs', quantity: 8, unit: 'pieces', category: 'protein' },
      { name: 'soy sauce', quantity: 0.5, unit: 'cup', category: 'pantry' },
      { name: 'white vinegar', quantity: 0.25, unit: 'cup', category: 'pantry' },
      { name: 'garlic', quantity: 8, unit: 'cloves', category: 'produce' },
      { name: 'bay leaves', quantity: 3, unit: 'pieces', category: 'spices' },
      { name: 'whole peppercorns', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'cooking oil', quantity: 1, unit: 'tbsp', category: 'pantry' },
      { name: 'steamed rice', quantity: 4, unit: 'cups', category: 'grains' },
    ],
    instructions: [
      'Combine chicken, soy sauce, vinegar, crushed garlic, bay leaves, and peppercorns in a pot.',
      'Bring to a boil, then reduce heat, cover, and simmer for 25 minutes.',
      'Remove chicken from the sauce. Heat oil in a pan and sear the chicken until the skin is crispy.',
      'Reduce the remaining sauce in the pot until slightly thickened.',
      'Pour sauce over the seared chicken and serve with steamed rice.',
    ],
    created_at: ts(15),
    updated_at: ts(15),
  },

  // 16 — Spanish
  {
    id: makeId(16),
    user_id: DEMO_USER_ID,
    title: 'Seafood Paella',
    description: 'Classic Spanish rice dish with shrimp, mussels, and saffron, cooked in a wide pan.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 20,
    cook_time_minutes: 35,
    calories_per_serving: 520,
    protein_per_serving: 32,
    carbs_per_serving: 60,
    fat_per_serving: 14,
    tags: ['spanish', 'seafood', 'rice'],
    ingredients: [
      { name: 'bomba or arborio rice', quantity: 300, unit: 'g', category: 'grains' },
      { name: 'shrimp', quantity: 300, unit: 'g', category: 'protein' },
      { name: 'mussels', quantity: 300, unit: 'g', category: 'protein' },
      { name: 'squid', quantity: 150, unit: 'g', category: 'protein' },
      { name: 'saffron threads', quantity: 1, unit: 'pinch', category: 'spices' },
      { name: 'chicken broth', quantity: 4, unit: 'cups', category: 'pantry' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'produce' },
      { name: 'tomato', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'smoked paprika', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'lemon', quantity: 1, unit: 'piece', category: 'produce' },
    ],
    instructions: [
      'Warm chicken broth and dissolve saffron in it.',
      'In a wide paella pan, heat olive oil and sauté onion and garlic.',
      'Add grated tomato and smoked paprika. Cook for 3 minutes.',
      'Sear squid rings briefly, then add rice and stir to coat in the sofrito.',
      'Pour in the saffron broth. Spread rice evenly — do NOT stir from this point.',
      'Cook on medium heat for 15 minutes. Nestle shrimp and mussels into the rice.',
      'Continue cooking until rice is done, mussels open, and a crispy crust (socarrat) forms on the bottom.',
      'Squeeze lemon over the top and let rest for 5 minutes before serving.',
    ],
    created_at: ts(16),
    updated_at: ts(16),
  },

  // 17 — Turkish
  {
    id: makeId(17),
    user_id: DEMO_USER_ID,
    title: 'Turkish Lentil Soup (Mercimek Çorbası)',
    description: 'Velvety red lentil soup with cumin and a squeeze of lemon — Turkey\'s most beloved soup.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    calories_per_serving: 220,
    protein_per_serving: 14,
    carbs_per_serving: 32,
    fat_per_serving: 5,
    tags: ['turkish', 'soup', 'lentils', 'vegan', 'healthy'],
    ingredients: [
      { name: 'red lentils', quantity: 250, unit: 'g', category: 'pantry' },
      { name: 'onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'carrot', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'potato', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'garlic', quantity: 2, unit: 'cloves', category: 'produce' },
      { name: 'cumin', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'butter or olive oil', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'vegetable broth', quantity: 5, unit: 'cups', category: 'pantry' },
      { name: 'lemon', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'paprika', quantity: 1, unit: 'tsp', category: 'spices' },
    ],
    instructions: [
      'Rinse red lentils until water runs clear.',
      'Sauté diced onion, carrot, and potato in butter until softened.',
      'Add garlic and cumin, cook for 1 minute.',
      'Add lentils and vegetable broth. Bring to a boil, then simmer for 20 minutes.',
      'Blend until completely smooth with an immersion blender.',
      'Season with salt, pepper, and a generous squeeze of lemon juice.',
      'Serve with a drizzle of paprika-infused butter (melt butter with paprika) on top.',
    ],
    created_at: ts(17),
    updated_at: ts(17),
  },

  // 18 — Peruvian
  {
    id: makeId(18),
    user_id: DEMO_USER_ID,
    title: 'Lomo Saltado',
    description: 'Peruvian stir-fried beef with onions, tomatoes, and french fries — a Chinese-Peruvian fusion classic.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    calories_per_serving: 510,
    protein_per_serving: 32,
    carbs_per_serving: 42,
    fat_per_serving: 22,
    tags: ['peruvian', 'beef', 'stir-fry', 'fusion'],
    ingredients: [
      { name: 'beef sirloin', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'red onion', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'tomatoes', quantity: 2, unit: 'pieces', category: 'produce' },
      { name: 'aji amarillo paste', quantity: 1, unit: 'tbsp', category: 'pantry' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'red wine vinegar', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'french fries', quantity: 300, unit: 'g', category: 'pantry' },
      { name: 'steamed rice', quantity: 2, unit: 'cups', category: 'grains' },
      { name: 'cilantro', quantity: 0.25, unit: 'cup', category: 'produce' },
    ],
    instructions: [
      'Cut beef into thick strips. Season with salt and pepper.',
      'Cook french fries until crispy (bake or fry). Set aside.',
      'Sear beef in a very hot pan in batches — don\'t overcrowd. Set aside.',
      'In the same pan, stir-fry sliced red onion until slightly charred.',
      'Add tomato wedges and aji amarillo paste. Cook for 2 minutes.',
      'Return beef, add soy sauce and vinegar. Toss on high heat for 30 seconds.',
      'Toss in french fries and fresh cilantro. Serve immediately with rice.',
    ],
    created_at: ts(18),
    updated_at: ts(18),
  },

  // 19 — Lebanese
  {
    id: makeId(19),
    user_id: DEMO_USER_ID,
    title: 'Falafel Wrap',
    description: 'Crispy chickpea fritters wrapped in warm pita with tahini, pickles, and fresh vegetables.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 30,
    cook_time_minutes: 15,
    calories_per_serving: 440,
    protein_per_serving: 16,
    carbs_per_serving: 52,
    fat_per_serving: 20,
    tags: ['lebanese', 'vegetarian', 'falafel', 'wrap'],
    ingredients: [
      { name: 'dried chickpeas (soaked overnight)', quantity: 300, unit: 'g', category: 'pantry' },
      { name: 'parsley', quantity: 1, unit: 'cup', category: 'produce' },
      { name: 'cilantro', quantity: 0.5, unit: 'cup', category: 'produce' },
      { name: 'onion', quantity: 0.5, unit: 'piece', category: 'produce' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'produce' },
      { name: 'cumin', quantity: 1, unit: 'tsp', category: 'spices' },
      { name: 'baking powder', quantity: 0.5, unit: 'tsp', category: 'pantry' },
      { name: 'pita bread', quantity: 4, unit: 'pieces', category: 'grains' },
      { name: 'tahini', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'tomato', quantity: 1, unit: 'piece', category: 'produce' },
      { name: 'cucumber', quantity: 0.5, unit: 'piece', category: 'produce' },
      { name: 'pickled turnip', quantity: 0.25, unit: 'cup', category: 'pantry' },
    ],
    instructions: [
      'Drain soaked chickpeas (do NOT use canned — they are too soft). Pat dry.',
      'Pulse chickpeas, parsley, cilantro, onion, garlic, and cumin in a food processor until coarse but holds together.',
      'Add baking powder and a pinch of salt. Refrigerate the mixture for 30 minutes.',
      'Shape into small patties or balls.',
      'Fry in oil at 350°F (175°C) for 3-4 minutes per side until deep golden.',
      'Make tahini sauce: thin tahini with water and lemon juice.',
      'Warm pita, fill with falafel, sliced tomato, cucumber, pickled turnip, and a drizzle of tahini sauce.',
    ],
    created_at: ts(19),
    updated_at: ts(19),
  },

  // 20 — American
  {
    id: makeId(20),
    user_id: DEMO_USER_ID,
    title: 'Classic Smash Burger',
    description: 'Thin, crispy-edged beef patties with melted American cheese, pickles, and special sauce.',
    source_url: null,
    source_type: 'manual',
    image_url: null,
    servings: 4,
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    calories_per_serving: 580,
    protein_per_serving: 34,
    carbs_per_serving: 36,
    fat_per_serving: 34,
    tags: ['american', 'burger', 'beef', 'quick'],
    ingredients: [
      { name: 'ground beef (80/20)', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'American cheese', quantity: 4, unit: 'slices', category: 'dairy' },
      { name: 'burger buns', quantity: 4, unit: 'pieces', category: 'grains' },
      { name: 'dill pickles', quantity: 8, unit: 'slices', category: 'pantry' },
      { name: 'mayonnaise', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'ketchup', quantity: 1, unit: 'tbsp', category: 'pantry' },
      { name: 'yellow mustard', quantity: 1, unit: 'tsp', category: 'pantry' },
      { name: 'onion', quantity: 0.5, unit: 'piece', category: 'produce' },
      { name: 'lettuce', quantity: 4, unit: 'leaves', category: 'produce' },
    ],
    instructions: [
      'Mix mayo, ketchup, and mustard to make the special sauce.',
      'Divide beef into 8 equal balls (two patties per burger).',
      'Heat a cast-iron skillet or flat griddle to very high heat.',
      'Place a ball on the skillet and immediately smash flat with a sturdy spatula. Season with salt and pepper.',
      'Cook for 2 minutes until the edges are deeply browned and crispy.',
      'Flip, place a slice of cheese on top, and cook for 1 more minute.',
      'Toast burger buns cut-side down on the griddle.',
      'Assemble: bottom bun, sauce, lettuce, two patties stacked, pickles, onion, top bun.',
    ],
    created_at: ts(20),
    updated_at: ts(20),
  },
];
